### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by realrk95** [AhmedLSayed9/deliverzler#1]
Hi there, am facing localizations issue on line 28, app_localization.dart:

`
Exception has occurred.
LateError (LateInitializationError: Field '_prefs@1795470296' has not been initialized.)
`

Also, there are some other bugs with StorageService similar to this. Like both storing and retrieving are not working.

I'm using Android 11, Redmi 9T Pro/K20 Pro and Flutter 2.10.1 with all other configurations as the same. Commenting out the errors works and login and everything else is working too.

Let me know how to fix this.

**Comment by AhmedLSayed9** [comment]
StorageService's sharedPreferences field wasn't initialized. I've committed a fix before https://github.com/AhmedLSayed9/deliverzler/commit/429ab4cc17f0dd168406a6ee12b55c1dc6700041.
Just ensure you initialize the StorageService in the ServiceInitializer class as shown in the commit then storing and retrieving will be working fine.

**Comment by realrk95** [comment]
Just tried the latest version too. Still isn't working. I've configured everything correctly. What do you mean by initialize StorageService? Isn't that being done in the code.

Thanks for making this public btw, huge time saver!

**Comment by AhmedLSayed9** [comment]
The issue was because `Theme & Localization` services was trying to use `Storage Service` before it's been initialized.
I've pushed a fix, Thanks @realrk95
